#!/bin/bash
drafts="$PWD/.drafts"
extension=".html"
author="Name Surname"
root="$PWD/root"
template="template.html"
indexTemplate="index.html"
indexFile="$root/index.html"
css="$PWD/style.css"

new() {
    read -erp "New blog title: " title
    anchorTitle=$(echo $title | sed "s/[[:blank:]]/-/g" | tr '[:upper:]' '[:lower:]')
    [[ -f "$drafts/$anchorTitle$extension" ]] && printf "File already exists\n" && exit

    cp "$template" "$drafts/$anchorTitle$extension"
    [[ ! -f "$drafts/style.css" ]] && cp "$css" "$drafts/"
    printf "Created a draft at $drafts/$anchorTitle$extension\n"

    date=$(date +"%d/%m/%y")

    content="<article id=\"$anchorTitle\">\n\t<h1>$title</h1>\n\t<p>\n\t\t<sub>$date</sub>\n\t\t<sub><i>$author</i></sub>\n\t\t<a href='#$anchorTitle'>[Anchor]</a>\n\t\t<a href='/$anchorTitle$extension'>[Standalone]</a>\n\t</p>\n\t<!--\$CONTENT-->\n</article>"

    sed -i "s/\$TITLE/$title/" "$drafts/$anchorTitle$extension"
    sed -i "s|\$CONTENT|$content|" "$drafts/$anchorTitle$extension"

    [[ "$EDITOR" ]] && "$EDITOR" "$drafts/$anchorTitle$extension" || printf "No default text editor found\n"
}

listAndSelectFile() {
    # List all files with target extension and number them, if no files are present exit
    files=`ls -1t "$drafts" | grep "$extension" | awk '{print NR,$0}'` && [[ "$files" = "" ]] && printf "No files found\n" && exit
    
    printf "$files\n"

    read -erp "Select file: " fileNum && [[ "$fileNum" = "" ]] && printf "Nothing selected\n" && exit

    selected_file=`printf "$files" | sed "${fileNum}q;d" | sed 's/[[:digit:]]\s//'`
}

remove() {
    listAndSelectFile ;
    rm "$drafts/$selected_file"
}

publish() {
    listAndSelectFile ;

    content=$(cat "$drafts/$selected_file" | awk '/<!--\$START-->/,/<!--\$END-->/' | sed 's/<!--\$START-->//' | sed 's/<!--\$END-->//')
    originalFile=$(cat "$indexFile" | awk '/<!--\$START-->/,/<!--\$END-->/' | sed 's/<!--\$START-->//' | sed 's/<!--\$END-->//')

    content=$(echo "$content" | tr -d \\n)
    content+="\n<!--\$END-->"

    sed -i "s|<!--\$END-->|$content|" "$indexFile" || exit

    mv "$drafts/$selected_file" "$root/"
}

edit() {
    listAndSelectFile ;

    [[ "$EDITOR" ]] && "$EDITOR" "$drafts/$selected_file" && printf "Draft saved in: $drafts/$selected_file\n" || printf "No default text editor found\n"
}

help() {
    printf "Blog CLI\nUsage:\n\tnew - creates new draft\n\tedit - edit existing draft\n\tlist - list existing drafts\n\tremove - remove existing draft\n\tpublish - publish existing draft\n"
}

[[ ! -d "$drafts" ]] && mkdir "$drafts"
[[ ! -d "$root" ]] && mkdir "$root"
[[ ! -f "$indexFile" ]] && cp "$indexTemplate" "$root"
[[ ! -f "$root/style.css" ]] && cp "$css" "$root/"

case "$1" in
    "new") new ;;
    "edit") edit ;;
    "list") listAndSelectFile ;;
    "remove") remove ;;
    "publish") publish ;;
    "help") help ;;
    *) help ;;
esac